subscribe-url: http://your-service-provider
proxy-providers:
  服务提供商-1:
    url: http://your-service-provider
    interval: 600
  # 服务提供商-2:
  #   url: http://your-another-service-provider
  #   interval: 600

proxy-groups:
  # 功能分组
  - name: 选择代理
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/mini/Proxy.png
    type: select
    proxies: &proxies
      - 自动选择
      - HK 香港
      - TW 台湾
      - SG 新加坡
      - JP 日本
      - US 美国
      - DIRECT

  - name: Netflix
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/mini/Netflix.png
    type: select
    proxies: *proxies

  - name: Disney+
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/mini/Disney%2B.png
    type: select
    proxies: *proxies

  - name: Spotify
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/mini/Spotify.png
    type: select
    proxies: *proxies

  - name: YouTube
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/mini/YouTube.png
    type: select
    proxies: *proxies

  - name: Speedtest
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/mini/Speedtest.png
    type: select
    proxies: *proxies

  - name: 默认
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/mini/Final.png
    type: select
    proxies:
      - 选择代理
      - DIRECT

  # 基于地区分组
  - name: HK 香港
    filter: "港|🇭🇰|HK|(?i)Hong"
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/mini/Hong_Kong.png
    interval: 120
    lazy: true
    tolerance: 50
    type: url-test
    url: http://cp.cloudflare.com/generate_204
    include-all: true

  - name: TW 台湾
    filter: "台|🇨🇳|🇹🇼|湾|TW|(?i)Taiwan"
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/mini/Taiwan.png
    interval: 120
    lazy: true
    tolerance: 50
    type: url-test
    url: http://cp.cloudflare.com/generate_204
    include-all: true

  - name: SG 新加坡
    filter: "新加坡|坡|狮城|🇸🇬|SG|(?i)Singapore"
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/mini/Singapore.png
    interval: 120
    lazy: true
    tolerance: 50
    type: url-test
    url: http://cp.cloudflare.com/generate_204
    include-all: true

  - name: JP 日本
    filter: "日|🇯🇵|东京|JP|(?i)Japan"
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/mini/Japan.png
    interval: 120
    lazy: true
    tolerance: 50
    type: url-test
    url: http://cp.cloudflare.com/generate_204
    include-all: true

  - name: US 美国
    filter: "美|🇺🇲|US|(?i)States|American"
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/mini/United_States.png
    interval: 120
    lazy: true
    tolerance: 50
    type: url-test
    url: http://cp.cloudflare.com/generate_204
    include-all: true

  - name: 自动选择
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/mini/Proxy.png
    interval: 120
    lazy: true
    tolerance: 50
    type: url-test
    url: http://cp.cloudflare.com/generate_204
    include-all: true

rules:
  - SCRIPT,quic,REJECT

  # Netflix
  - RULE-SET,netflix,Netflix
  # Disney+
  - RULE-SET,disney,Disney+
  # Spotify
  - RULE-SET,spotify,Spotify
  # Speedtest
  - RULE-SET,speedtest,Speedtest
  # GitHub
  - RULE-SET,github,选择代理
  # Telegram
  - IP-ASN,62014,选择代理,no-resolve
  - IP-ASN,59930,选择代理,no-resolve
  - IP-ASN,44907,选择代理,no-resolve
  - IP-ASN,211157,选择代理,no-resolve
  - PROCESS-NAME,Telegram.exe,选择代理
  - PROCESS-NAME,Telegram,选择代理
  - RULE-SET,telegram,选择代理
  # YouTube
  - RULE-SET,youtube,YouTube
  # Google
  - RULE-SET,google,选择代理
  # Twitter
  - RULE-SET,twitter,选择代理
  - DOMAIN-SUFFIX,tapbots.com,选择代理
  # Instagram
  - RULE-SET,instagram,选择代理
  # Facebook
  - RULE-SET,facebook,选择代理
  # Steam
  - RULE-SET,steam@cn,DIRECT
  - RULE-SET,steam,选择代理
  # Apple LBS
  - DOMAIN-SUFFIX,iphone-ld.apple.com,DIRECT
  - DOMAIN-SUFFIX,lcdn-locator.apple.com,DIRECT
  - DOMAIN-SUFFIX,lcdn-registration.apple.com,DIRECT
  - DOMAIN-SUFFIX,push.apple.com,DIRECT
  # Apple OCSP
  - PROCESS-NAME,trustd,选择代理
  # Microsoft
  - RULE-SET,microsoft@cn,DIRECT
  - RULE-SET,microsoft,选择代理
  - RULE-SET,xbox,选择代理
  # common proxy utils
  - PROCESS-NAME,v2ray,DIRECT
  - PROCESS-NAME,Surge,DIRECT
  - PROCESS-NAME,ss-local,DIRECT
  - PROCESS-NAME,privoxy,DIRECT
  - PROCESS-NAME,trojan,DIRECT
  - PROCESS-NAME,trojan-go,DIRECT
  - PROCESS-NAME,naive,DIRECT
  - PROCESS-NAME,CloudflareWARP,DIRECT
  - PROCESS-NAME,Cloudflare WARP,DIRECT
  - IP-CIDR,162.159.193.0/24,DIRECT,no-resolve
  - PROCESS-NAME,p4pclient,DIRECT
  - PROCESS-NAME,Thunder,DIRECT
  - PROCESS-NAME,DownloadService,DIRECT
  - PROCESS-NAME,qbittorrent,DIRECT
  - PROCESS-NAME,Transmission,DIRECT
  - PROCESS-NAME,fdm,DIRECT
  - PROCESS-NAME,aria2c,DIRECT
  - PROCESS-NAME,Folx,DIRECT
  - PROCESS-NAME,NetTransport,DIRECT
  - PROCESS-NAME,uTorrent,DIRECT
  - PROCESS-NAME,WebTorrent,DIRECT

  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,默认
script:
  shortcuts:
    quic: network == 'udp' and dst_port == 443
dns:
  default-nameserver:
    - 114.114.115.115
    - 119.28.28.28
    - 223.6.6.6
    - system
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
log-level: info
mode: rule

rule-providers:
  netflix:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/netflix.yaml
  disney:
    behavior: domain
    interval: 86400
    type: http
    url: https://rules.kr328.app/disney.yaml
  spotify:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/spotify.yaml
  speedtest:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/speedtest.yaml
  github:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/github.yaml
  telegram:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/telegram.yaml
  youtube:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/youtube.yaml
  google:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/google.yaml
  twitter:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/twitter.yaml
  instagram:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/instagram.yaml
  facebook:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/facebook.yaml
  steam:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/steam.yaml
  steam@cn:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/steam@cn.yaml
  microsoft:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/microsoft.yaml
  microsoft@cn:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/microsoft@cn.yaml
  xbox:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/xbox.yaml
