mixed-port: 7890
allow-lan: true
bind-address: '*'
ipv6: false
resolve-hostnames: true

proxies:
  - name: LV 2
    type: socks5
    server: 87.99.68.28
    port: 30230
    username: p30230
    password: Kejs777

proxy-groups:
  - name: Main
    type: select
    proxies:
      - DIRECT
      - LV 2
  - name: Default
    type: fallback
    proxies:
      - DIRECT
      - LV 2

rules:
  - DOMAIN-KEYWORD,t.me,LV 2,no-track
  - DOMAIN-KEYWORD,telegram,LV 2,no-track
  - PROCESS-NAME,Telegram,LV 2,no-track
  - PROCESS-NAME,Anty Helper,LV 2,no-track
  - PROCESS-NAME,Dolphin Anty,LV 2,no-track
  - DOMAIN-KEYWORD,browser,LV 2,no-track
  - IP-CIDR,5.28.195.1/32,LV 2,no-track
  - PROCESS-NAME,Dolphin Anty Helper,LV 2,no-track
  - DOMAIN-KEYWORD,kaspersky,DIRECT,no-track
  - PROCESS-NAME,com.kaspersky.kav,DIRECT,no-track
  - PROCESS-NAME,kaspersky,DIRECT,no-track
  - PROCESS-NAME,kavd,DIRECT,no-track
  - DOMAIN-KEYWORD,cloudflare,LV 2,no-track
  - DOMAIN-KEYWORD,adspower,LV 2,no-track
  - PROCESS-NAME,AdsPower Global,LV 2,no-track
  - DOMAIN-KEYWORD,google,LV 2,no-track
  - DOMAIN-KEYWORD,x10,LV 2,no-track
  - DOMAIN-KEYWORD,facebook,LV 2,no-track
  - DOMAIN-KEYWORD,instagram,LV 2,no-track
  - DOMAIN-KEYWORD,smshub,LV 2,no-track
  - DOMAIN-KEYWORD,notion,LV 2,no-track
  - DOMAIN-KEYWORD,openai,LV 2,no-track
  - DOMAIN-KEYWORD,proton,LV 2,no-track
  - DOMAIN-KEYWORD,youtube,LV 2,no-track
  - DOMAIN-KEYWORD,icloud.com,DIRECT,no-track
  - DOMAIN-KEYWORD,apple.com,DIRECT,no-track
  - DOMAIN-KEYWORD,1password,DIRECT,no-track
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Default

dns:
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query
  enhanced-mode: redir-host

log-level: info
mode: rule

script:
  shortcuts:
    quic: network == 'udp' and dst_port == 443
  bypass:
    - process-name: com.kaspersky.kav
    - process-name: kavd
    - process-name: kaspersky