subscribe-url: http://your-service-provider
proxy-providers:
  服务提供商-1:
    url: http://your-service-provider
    interval: 600
  # 服务提供商-2:
  #   url: http://your-another-service-provider
  #   interval: 600
proxy-groups:
  # 功能分组
  - name: 选择代理
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/mini/Proxy.png
    type: select
    proxies: &proxies
      - 自动选择
      - HK 香港
      - TW 台湾
      - SG 新加坡
      - JP 日本
      - US 美国
      - DIRECT
  - name: Netflix
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/mini/Netflix.png
    type: select
    proxies: *proxies
  - name: Disney+
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/mini/Disney%2B.png
    type: select
    proxies: *proxies
  - name: Spotify
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/mini/Spotify.png
    type: select
    proxies: *proxies
  - name: YouTube
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/mini/YouTube.png
    type: select
    proxies: *proxies
  - name: Speedtest
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/mini/Speedtest.png
    type: select
    proxies: *proxies
  - name: 默认
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/mini/Final.png
    type: select
    proxies:
      - 选择代理
      - DIRECT
  # 基于地区分组
  - name: HK 香港
    filter: "港|🇭🇰|HK|(?i)Hong"
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/mini/Hong_Kong.png
    interval: 120
    lazy: true
    tolerance: 50
    type: url-test
    url: http://cp.cloudflare.com/generate_204
    include-all: true
  - name: TW 台湾
    filter: "台|🇨🇳|🇹🇼|湾|TW|(?i)Taiwan"
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/mini/Taiwan.png
    interval: 120
    lazy: true
    tolerance: 50
    type: url-test
    url: http://cp.cloudflare.com/generate_204
    include-all: true
  - name: SG 新加坡
    filter: "新加坡|坡|狮城|🇸🇬|SG|(?i)Singapore"
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/mini/Singapore.png
    interval: 120
    lazy: true
    tolerance: 50
    type: url-test
    url: http://cp.cloudflare.com/generate_204
    include-all: true
  - name: JP 日本
    filter: "日|🇯🇵|东京|JP|(?i)Japan"
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/mini/Japan.png
    interval: 120
    lazy: true
    tolerance: 50
    type: url-test
    url: http://cp.cloudflare.com/generate_204
    include-all: true
  - name: US 美国
    filter: "美|🇺🇲|US|(?i)States|American"
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/mini/United_States.png
    interval: 120
    lazy: true
    tolerance: 50
    type: url-test
    url: http://cp.cloudflare.com/generate_204
    include-all: true
  - name: 自动选择
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/mini/Proxy.png
    interval: 120
    lazy: true
    tolerance: 50
    type: url-test
    url: http://cp.cloudflare.com/generate_204
    include-all: true
rules:
  - DOMAIN-KEYWORD,test2,LV 2,no-track
  - DOMAIN-KEYWORD,test,LV 2,no-track
  - PROCESS-NAME,AdsPower Global,LV 2,no-track
  - DOMAIN-KEYWORD,monolead,LV 2,no-track
  - DOMAIN-KEYWORD,cpatoday,LV 2,no-track
  - DOMAIN-KEYWORD,betterdisplay,LV 2,no-track
  - DOMAIN-KEYWORD,nektony,LV 2,no-track
  - DOMAIN-KEYWORD,ytimg,LV 2,no-track
  - DOMAIN-KEYWORD,ggpht,LV 2,no-track
  - DOMAIN-KEYWORD,googlevideo,LV 2,no-track
  - DOMAIN-KEYWORD,binance,LV 2,no-track
  - PROCESS-NAME,ig.com,LV 2,no-track
  - DOMAIN-KEYWORD,canva,LV 2,no-track
  - DOMAIN-KEYWORD,git,LV 2,no-track
  - DOMAIN-KEYWORD,whoer.net,LV 2,no-track
  - DOMAIN-KEYWORD,fb.com,LV 2,no-track
  - DOMAIN-KEYWORD,facebook,LV 2,no-track
  - DOMAIN-KEYWORD,instagram,LV 2,no-track
  - DOMAIN-KEYWORD,stripe,LV 2,no-track
  - DOMAIN-KEYWORD,smshub,LV 2,no-track
  - DOMAIN-KEYWORD,x10,LV 2,no-track
  - PROCESS-NAME,AdsPower Global Helper,LV 2,no-track
  - PROCESS-NAME,AdsPowerToolMerge,LV 2,no-track
  - DOMAIN-KEYWORD,devmate.com,LV 2,no-track
  - PROCESS-NAME,tor,LV 2,no-track
  - PROCESS-NAME,Notion Helper,LV 2,no-track
  - DOMAIN-KEYWORD,notion,LV 2,no-track
  - PROCESS-NAME,Notion,LV 2,no-track
  - PROCESS-NAME,Pachca,DIRECT,no-track
  - PROCESS-NAME,Pachca Helper,DIRECT,no-track
  - PROCESS-NAME,ChatGPTHelper,LV 2,no-track
  - PROCESS-NAME,com.kaspersky.kav,DIRECT,no-track
  - PROCESS-NAME,Asana Helper,LV 2,no-track
  - PROCESS-NAME,PuntoSwitcher,DIRECT,no-track
  - PROCESS-NAME,kaspersky,DIRECT,no-track
  - DOMAIN-KEYWORD,browserleaks,LV 2,no-track
  - DOMAIN-KEYWORD,icloud.com,DIRECT,no-track
  - DOMAIN-KEYWORD,apple.com,DIRECT,no-track
  - DOMAIN-KEYWORD,1password,DIRECT,no-track
  - PROCESS-NAME,kavd,DIRECT,no-track
  - DOMAIN-KEYWORD,kaspersky,DIRECT,no-track
  - DOMAIN-KEYWORD,youtube,LV 2,no-track
  - DOMAIN-KEYWORD,proton,LV 2,no-track
  - DOMAIN-KEYWORD,confluence,LV 2,no-track
  - DOMAIN-KEYWORD,jira,LV 2,no-track
  - DOMAIN-KEYWORD,atlassian,LV 2,no-track
  - DOMAIN-KEYWORD,airtable,LV 2,no-track
  - PROCESS-NAME,asana,LV 2,no-track
  - DOMAIN-KEYWORD,asana,LV 2,no-track
  - PROCESS-NAME,chatgpt,LV 2,no-track
  - DOMAIN-KEYWORD,chatgpt,LV 2,no-track
  - DOMAIN-KEYWORD,whoer.net,LV 2,no-track
  - DOMAIN-KEYWORD,sentry.io,LV 2,no-track
  - DOMAIN-KEYWORD,openai,LV 2,no-track
  - DOMAIN-KEYWORD,2ip,LV 2,no-track
  - DOMAIN-KEYWORD,deepl,LV 2,no-track
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Default
script:
  shortcuts:
    quic: network == 'udp' and dst_port == 443
dns:
  default-nameserver:
    - 114.114.115.115
    - 119.28.28.28
    - 223.6.6.6
    - system
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
log-level: info
mode: rule
rule-providers:
  netflix:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/netflix.yaml
  disney:
    behavior: domain
    interval: 86400
    type: http
    url: https://rules.kr328.app/disney.yaml
  spotify:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/spotify.yaml
  speedtest:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/speedtest.yaml
  github:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/github.yaml
  telegram:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/telegram.yaml
  youtube:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/youtube.yaml
  google:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/google.yaml
  twitter:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/twitter.yaml
  instagram:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/instagram.yaml
  facebook:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/facebook.yaml
  steam:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/steam.yaml
  steam@cn:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/steam@cn.yaml
  microsoft:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/microsoft.yaml
  microsoft@cn:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/microsoft@cn.yaml
  xbox:
    behavior: domain
    interval: 86400
    url: https://rules.kr328.app/xbox.yaml
