mixed-port: 7890
allow-lan: true
bind-address: '*'
ipv6: false
resolve-hostnames: true

proxies:
  - name: LV 2
    type: socks5
    server: 87.99.68.28
    port: 30230
    username: p30230
    password: Kejs777

proxy-groups:
  - name: Main
    type: select
    proxies:
      - DIRECT
      - LV 2
  - name: Default
    type: fallback
    proxies:
      - DIRECT
      - LV 2

rules:
  - DOMAIN-KEYWORD,t.me,LV 2
  - DOMAIN-KEYWORD,telegram,LV 2
  - PROCESS-NAME,Anty Helper,LV 2
  - PROCESS-NAME,Dolphin Anty,LV 2
  - DOMAIN-KEYWORD,browser,LV 2
  - PROCESS-NAME,Telegram,LV 2
  - PROCESS-NAME,com.kaspersky.kav,DIRECT
  - PROCESS-NAME,kaspersky,DIRECT
  - PROCESS-NAME,kavd,DIRECT
  - DOMAIN-KEYWORD,kaspersky,DIRECT
  - DOMAIN-KEYWORD,rusich-nsk.ru,LV 2
  - DOMAIN-KEYWORD,hydraproxy,LV 2
  - DOMAIN-KEYWORD,sav,LV 2
  - DOMAIN-KEYWORD,anty,LV 2
  - DOMAIN-KEYWORD,dolphin,LV 2
  - PROCESS-NAME,Dolphin Anty Helper,LV 2
  - DOMAIN-KEYWORD,replicate,LV 2
  - PROCESS-NAME,SunBrowser Helper,LV 2
  - DOMAIN-KEYWORD,cloudflare,LV 2
  - DOMAIN-KEYWORD,adspower,LV 2
  - PROCESS-NAME,AdsPower Global,LV 2
  - DOMAIN-KEYWORD,google,LV 2
  - DOMAIN-KEYWORD,monolead,LV 2
  - DOMAIN-KEYWORD,cpatoday,LV 2
  - DOMAIN-KEYWORD,betterdisplay,LV 2
  - DOMAIN-KEYWORD,nektony,LV 2
  - DOMAIN-KEYWORD,ytimg,LV 2
  - DOMAIN-KEYWORD,ggpht,LV 2
  - DOMAIN-KEYWORD,googlevideo,LV 2
  - DOMAIN-KEYWORD,binance,LV 2
  - DOMAIN-KEYWORD,canva,LV 2
  - DOMAIN-KEYWORD,git,LV 2
  - DOMAIN-KEYWORD,fb.com,LV 2
  - DOMAIN-KEYWORD,facebook,LV 2
  - DOMAIN-KEYWORD,instagram,LV 2
  - DOMAIN-KEYWORD,stripe,LV 2
  - DOMAIN-KEYWORD,smshub,LV 2
  - DOMAIN-KEYWORD,x10,LV 2
  - PROCESS-NAME,AdsPower Global Helper,LV 2
  - PROCESS-NAME,AdsPowerToolMerge,LV 2
  - DOMAIN-KEYWORD,devmate.com,LV 2
  - PROCESS-NAME,tor,LV 2
  - PROCESS-NAME,Notion Helper,LV 2
  - DOMAIN-KEYWORD,notion,LV 2
  - PROCESS-NAME,Notion,LV 2
  - PROCESS-NAME,Pachca,DIRECT
  - PROCESS-NAME,Pachca Helper,DIRECT
  - PROCESS-NAME,ChatGPTHelper,LV 2
  - PROCESS-NAME,Asana Helper,LV 2
  - PROCESS-NAME,PuntoSwitcher,DIRECT
  - DOMAIN-KEYWORD,browserleaks,LV 2
  - DOMAIN-KEYWORD,icloud.com,DIRECT
  - DOMAIN-KEYWORD,apple.com,DIRECT
  - DOMAIN-KEYWORD,1password,DIRECT
  - DOMAIN-KEYWORD,youtube,LV 2
  - DOMAIN-KEYWORD,proton,LV 2
  - DOMAIN-KEYWORD,confluence,LV 2
  - DOMAIN-KEYWORD,jira,LV 2
  - DOMAIN-KEYWORD,atlassian,LV 2
  - DOMAIN-KEYWORD,airtable,LV 2
  - PROCESS-NAME,asana,LV 2
  - DOMAIN-KEYWORD,asana,LV 2
  - PROCESS-NAME,chatgpt,LV 2
  - DOMAIN-KEYWORD,chatgpt,LV 2
  - DOMAIN-KEYWORD,whoer.net,LV 2
  - DOMAIN-KEYWORD,sentry.io,LV 2
  - DOMAIN-KEYWORD,openai,LV 2
  - DOMAIN-KEYWORD,2ip,LV 2
  - DOMAIN-KEYWORD,deepl,LV 2
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Default

dns:
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query
  enhanced-mode: fake-ip

log-level: info
mode: rule

script:
  shortcuts:
    quic: network == 'udp' and dst_port == 443
  bypass:
    - process-name: com.kaspersky.kav
    - process-name: kavd
    - process-name: kaspersky